# Generated by Django 4.1.1 on 2022-09-26 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funolympic', '0005_remove_category_user_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
